### ISSUE TITLE
Apache Cotton support

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/mantl-universe#11]
As @PeterLamar points out in https://github.com/CiscoCloud/microservices-infrastructure/issues/83, many folks use and are familiar with MySQL. This isn't urgent, but it might be nice to support [Apache Cotton](http://incubator.apache.org/projects/cotton.html), Apache's MySQL on Mesos framework. We can then include an example app on Mantl with it :)

**Comment by ryane** [comment]
it looks like this project may is not being maintained anymore. It was retired as an Apache project. http://incubator.apache.org/projects/cotton.html
