### ISSUE TITLE
Documentation: CONTRIBUTING.md

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/mantl-universe#12]
How do we go about developing support for Mesos frameworks on Mantl? What in the world are the .json files in this repo? Can we document the process that you've been using to develop these configs so the rest of us can take some load off your back @ryane?

**Comment by ryane** [comment]
@siddharthist I added details about the packaging in #16. do you mind taking a look and see if it is clear or if it needs some updating?

More details about how Mantl API works with the packages is in https://github.com/CiscoCloud/mantl-api/pull/24 also. Thanks!

**Comment by langston-barrett** [comment]
Both of those look really, really good! All the links are very nice and should make it dead simple to get started contributing frameworks.
