### ISSUE TITLE
Spark package

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/mantl-universe#28]
Is anyone working on getting Spark in mantl-universe? I am working to deploying Spark on MANTL, having a package here it might be the way to go. I could put some extra effort in making a PR if you guys think it would be useful.

**Comment by ryane** [comment]
Yes, please. It would be really nice to have. Let me know if I can help.

**Comment by mcapuccini** [comment]
Just figured this out #27, I might test if that works first!

**Comment by ryane** [comment]
code was contributed in #30. merged manually into the version-0.6 branch
