### ISSUE TITLE
List supported packages in the README

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/mantl-universe#8]
The [mantl-api README](https://github.com/CiscoCloud/mantl-api) states that "mantl-universe contains the list of packages that work out-of-the-box on Mantl today". We have no list! 

I assume this list is just all the subfolders of repo/packages?

**Comment by ryane** [comment]
Yes, right now it is just the repo/packages. Definitely need to improve the readme in this repo. Thanks bringing this up
