### ISSUE TITLE
Kibana 4 support

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/mantl-universe#9]
As per https://github.com/CiscoCloud/microservices-infrastructure/issues/55, @keithchambers has requested support for the Kibana framework on Mantl.

**Comment by corebug** [comment]
We're adding this via https://github.com/CiscoCloud/mantl-universe/pull/22.

**Comment by ryane** [comment]
mesos framework version: https://github.com/CiscoCloud/mantl-universe/tree/version-0.7/repo/packages/K/kibana-mesos/0
non-framework version: https://github.com/CiscoCloud/mantl-universe/tree/version-0.7/repo/packages/K/kibana/0
